projects:
  - name: Percorsi partecipativi alla normativa regionale PC Abruzzo
    description: |
      Collabora alla stesura della normativa regionale in materia di Protezione Civile.
    documents:
      - tupc
    short_name: PPNRA
    website: 
    tags:
      - 
      - 
      - 
