projects:
  - name: APC Abruzzo: percorsi partecipativi alla normativa regionale.
    description: |
      Collabora alla stesura della normativa regionale in materia di Protezione Civile.
    documents:
      - tupc-docs
    short_name: PPNRA
    website: 
    tags:
      - 
      - 
      - 
